import { Inter } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}
      </body>
      <Script src="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      <Script src="https://fonts.googleapis.com/icon?family=Material+Icons" />
    </html>
  );
}
